name: Python Application Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy psutil memory_profiler

    - name: Run script and capture output
      run: |
        python python.py > output.log 2>&1
    
    - name: Print output log
      run: cat output.log

    - name: Upload output log
      uses: actions/upload-artifact@v4
      with:
        name: output-log
        path: output.log
